environment.name=test
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.config.import=env.properties


jwt.secret=${ACCESS_TOKEN}
jwt.refresh=${REFRESH_TOKEN}
jwt.expiration=3600000


# set upload file size
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.resolve-lazily=false

# upload image directory

file.upload-profile = ${PATH_FILE_UPLOAD}