spring.application.name=marketplace

spring.profiles.active=${PROFILE_STATE}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=jdbc:postgresql://${DB_DATASOURCE_URL}

# check nulable with hibernate
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt.access.token=${ACCESS_TOKEN}
jwt.refresh.token=${REFRESH_TOKEN}
jwt.expiration=1200000
jwt.refresh_expiration=172800000

# set upload file size
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.resolve-lazily=false

# upload image directory
file.upload.profile=${FILE_UPLOAD_PATH}


spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}
spring.redis.database=0

admin.name=${ADMIN_NAME}
admin.password=${ADMIN_PASSWORD}
admin.email=${ADMIN_EMAIL}

spring.h2.console.enabled=true